# name: Deploy Intervall app

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   packages: write
#   id-token: write

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Modules
#         run: npm install
#       - name: Build
#         run: npm run build
#       - name: Setup pages
#         uses: actions/configure-pages@v3
#       - name: upload dist folder
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: "./dist"
#       - name: Deploy to github pages
#         uses: actions/deploy-pages@v1

#         name: Deploy React app

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
